#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
export PYTHONPATH="${REPO_ROOT}/src:${PYTHONPATH:-}"

REPORT_TMP="$(mktemp)"
trap 'rm -f "${REPORT_TMP}"' EXIT

python3 -m agentic_sql_converter.cli.main analyze "${SCRIPT_DIR}/legacy_postgres_query.sql" --dialect postgres \
  >"${REPORT_TMP}"

export DEMO_ANALYSIS_TMP="${REPORT_TMP}"
export DEMO_CASE_DIR="${SCRIPT_DIR}"

python3 <<'PY'
from __future__ import annotations

import json
import os
from pathlib import Path

payload_path = os.environ["DEMO_ANALYSIS_TMP"]
root = Path(os.environ["DEMO_CASE_DIR"]).resolve()

data = json.loads(Path(payload_path).read_text(encoding="utf-8"))

(root / "expected_analysis_report.json").write_text(
    json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
    encoding="utf-8",
)
(root / "expected_dependency_graph.json").write_text(
    json.dumps(data["dependency_graph"], indent=2, sort_keys=True, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

summary = data["summary"]
validation = data["validation"]
deps = data["dependency_graph"]
risk_categories = data.get("risk_categories", [])
risk_findings = data.get("risk_findings", [])
md_lines = [
    "# Migration validation report (synthetic demo)",
    "",
    "This report is regenerated by `examples/migration_case/run_demo.sh`. ",
    "It summarizes local, offline analysis for the fixture SQL ",
    "`legacy_postgres_query.sql`: parse readiness, CTE footprint, ",
    "dependency wiring, and a lightweight structural migration-risk label.",
    "",
    "## Fixture",
    "",
    "- Source dialect (for SQLGlot read): Postgres",
    "",
    "## Parse readiness",
    "",
    f"- Valid parse: `{validation['is_valid']}`",
    f"- Statement count (top-level parsed): `{validation['statement_count']}`",
    f"- Validation errors: `{validation['error_count']}`",
    "",
    "## Structural cues",
    "",
    "Notes:",
    "",
]
for note in summary.get("notes", []):
    md_lines.append(f"- {note}")
md_lines.extend(
    [
        "",
        "## Deterministic migration risk signals",
        "",
        f"- Canonical bucket (mirrors CLI `risk_level`): **{data['risk_level']}**",
        f"- Tagged categories ({len(risk_categories)}): "
        + (", ".join(f"`{c}`" for c in risk_categories) or "_none besides structural notes above_"),
        "",
    ]
)

if risk_findings:
    md_lines.extend(
        [
            "Structured findings:",
            "",
        ]
    )
    for item in sorted(risk_findings, key=lambda row: (row["category"], row["message"])):
        md_lines.append(
            f"- `{item['category']}` · *{item['severity']}*: {item['message']}"
        )
    md_lines.append("")

md_lines.extend(
    [
        "This artifact does **not** apply target dialect rewrites—it only inventories "
        "parse + graph context for reviewers.",
        "",
        "## CTE footprint",
        "",
        f"- CTE definitions: `{summary['cte_count']}`",
        f"- Dependencies edges (CTE/table): `{summary['dependency_edge_count']}`",
        f"- Outer table refs (non-CTE): `{summary['table_count']}`",
        f"- CTE cycle detected in graph: `{summary['has_cycle']}`",
        "",
        "## Dependency graph excerpt",
        "",
        "Directed edges:",
        "",
    ]
)
for edge in deps.get("edges", []):
    md_lines.append(
        f"- `{edge['from']}` → `{edge['to']}` ({edge['dependency_type']})"
    )
md_lines.extend(
    [
        "",
        "## Rewrite / conversion status",
        "",
        f"- Registered deterministic rewrite passes: `{summary['registered_rewrite_pass_count']}` ",
        "(none applied in this MVP analysis path)",
        "",
        "## Not covered by this harness",
        "",
        "- Semantic validation against a live warehouse catalog",
        "- Cost or SLA guarantees",
        "- Automatic cross-dialect SQL rewriting",
        "- LLMs, MCP tooling, credentials, or network calls",
        "",
    ]
)
(root / "validation_report.md").write_text("\n".join(md_lines), encoding="utf-8")

print("Demo artifacts regenerated under", root)
PY

echo ""
echo "Wrote deterministic demo artifacts:"
echo "  ${SCRIPT_DIR}/expected_analysis_report.json"
echo "  ${SCRIPT_DIR}/expected_dependency_graph.json"
echo "  ${SCRIPT_DIR}/validation_report.md"
